services:
  - type: web
    name: horse-racing-platform
    runtime: python
    buildCommand: "./render-build.sh"
    startCommand: "cd src && python main.py"
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mob1e
          property: connectionString
      - key: RACING_API_USERNAME
        sync: false
      - key: RACING_API_PASSWORD
        sync: false
      - key: RACING_API_BASE_URL
        value: https://api.theracingapi.com
      - key: PORT
        value: "8000"